name: build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag of go-ipfs'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get ref
        id: ref
        run: |
          REF="${{ github.event.inputs.tag }}"
          echo "::set-output name=value::$(echo ${REF:-master})"
        shell: bash
      - name: Get tag
        id: tag
        run: |
          REF="${{ github.event.inputs.tag }}"
          echo "::set-output name=value::$(echo ${REF:-nightly})"
        shell: bash

      - uses: actions/checkout@v2
        with:
          repository: ipfs/go-ipfs
          path: go-ipfs
          ref: "${{ steps.ref.outputs.value }}"
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./go-ipfs
          file: ./go-ipfs/Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=odanado/go-ipfs:latest
          cache-to: type=inline
          tags: |
            "odanado/go-ipfs:${{ steps.tag.outputs.value }}"
